### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ederag** [campagnola/pyoptics#1]
[geoptics](https://github.com/ederag/geoptics) was started years before knowing about pyoptics.
Otherwise I would have contributed to pyoptics directly, instead.

Our projects are very similar (python, Qt, 2D, geometrical optics), but advanced in different directions.
For instance geoptics has non-sequential ray tracing, mouse control of sources, and package infrastructure,
and a "serious game" emphasis.
While pyoptics has tools (such as the glasses database) for quick research design,
mouse control of lenses orientation, animations, additive color mixing of rays, and more.

So there is room for collaboration. I would even gladly pass the driving wheel to someone else.

But could the license of pyoptics be specified first, hopefully [GPL-compatible](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses) ?

**Comment by campagnola** [comment]
Hi @ederag, I have added an MIT license file; you are welcome to take whatever you find useful! I'd agree that the glass DB and dispersion modeling would be an easy and useful addition to geoptics. I'd also be happy to offer advice / help implementing a more advanced UI, but I probably wouldn't try to reuse that code from pyoptics directly; it's not particularly well designed.
